---
- name: Macvlan | restart network
  command: /bin/true
  notify:
    - Macvlan | reload network
  when: not ansible_os_family in ["CoreOS", "Container Linux by CoreOS"]

- name: Macvlan | reload network
  service:
    name: >-
      {% if ansible_os_family == "RedHat" -%}
      network
      {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic" -%}
      systemd-networkd
      {%- elif ansible_os_family == "Debian" -%}
      networking
      {%- endif %}
    state: restarted
  when: not ansible_os_family in ["CoreOS", "Container Linux by CoreOS"] and kube_network_plugin not in ['canal', 'calico']
