Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-18.04-v0.virtualbox.box"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  end

end
