---
- hosts: kubernetes-cluster
  vars_files:
    - vars/config.yml
  tasks:
    - name: Copy files from yml 
      include_tasks: tasks/copy-file.yml
    - name: Copy files from task
      copy:
        src: ../files/
        dest: /home/iaktas/
        owner: iaktas
        group: iaktas
        mode: '0644'  
...
