---

crio_cgroup_manager: "{{ kubelet_cgroup_driver | default('cgroupfs') }}"

crio_seccomp_profile: ""
crio_runc_path: "/usr/bin/runc"
crio_conmon: "/usr/bin/conmon"

crio_required_version: "{{ kube_version | regex_replace('^v(?P<major>\\d+).(?P<minor>\\d+).(?P<patch>\\d+)$', '\\g<major>.\\g<minor>') }}"

crio_kubernetes_version_matrix:
  "1.18": "1.18"
  "1.17": "1.17"
  "1.16": "1.16"

crio_version: "{{ crio_kubernetes_version_matrix[crio_required_version] | default('1.17') }}"
