---
- name: Import Base Ubuntu Image {{item.name}}
  command: VBoxManage import {{ ova_path }} --vsys 0 --vmname {{ item.name }} --unit 11 --disk {{ disk_base_dir }}/{{ item.name }}.vmdk
- name: Run {{ item.name }} VM
  command: VBoxManage startvm {{ item.name }}
- name: Wait {{ item.name }} VM's IP
  command: VBoxManage guestproperty wait {{ item.name }} "/VirtualBox/GuestInfo/Net/0/V4/IP"
- name: Get {{ item.name }} VM's IP
  shell: VBoxManage guestproperty get {{ item.name }} "/VirtualBox/GuestInfo/Net/0/V4/IP" | cut -d ' ' -f2
  register: vm_ip
- name: Print {{ item.name }} VM IP
  debug:
    msg: "{{ item.name }} = '{{ vm_ip.stdout}}'"
- name: Wait {{ item.name }}'s SSH port
  wait_for:
    port: 22
    host: "{{ vm_ip.stdout }}"
- name: Add {{ item.name }} VM to [kubernetes-nodes] groups in inventory for further use in set-static-ip.yml
  add_host:
    name: "{{ item.name }}"
    groups: "kubernetes-nodes"
    ansible_host: "{{ vm_ip.stdout }}"
    ansible_user: iaktas
    ansible_ssh_pass: "{{ vm_ssh_password }}"
- name: Set Static IP for {{ item }} VM 
  include_tasks: set-static-ip.yml
...
