---
- name: Calculate etcd cert serial
  command: "openssl x509 -in {{ kube_cert_dir }}/apiserver-etcd-client.crt -noout -serial"
  register: "etcd_client_cert_serial_result"
  changed_when: false
  tags:
    - network

- name: Set etcd_client_cert_serial
  set_fact:
    etcd_client_cert_serial: "{{ etcd_client_cert_serial_result.stdout.split('=')[1] }}"
  tags:
    - network

- name: Ensure etcdctl binary is installed
  include_tasks: "{{ role_path }}/../../etcd/tasks/install_host.yml"
  vars:
    etcd_cluster_setup: true
