---
- name: Lookup node IP in kubernetes
  shell: >-
    {{ bin_dir }}/kubectl get nodes {{ node }}
    -o jsonpath='{range.status.addresses[?(@.type=="InternalIP")]}{.address}{"\n"}{end}'
  register: remove_node_ip
  when:
    - inventory_hostname in groups['etcd']
    - ip is not defined
    - access_ip is not defined
  delegate_to: "{{ groups['etcd']|first }}"
  failed_when: false

- name: Delete node
  command: "{{ bin_dir }}/kubectl delete node {{ inventory_hostname }}"
  delegate_to: "{{ groups['kube-master']|first }}"
  ignore_errors: yes
