# ansible-playbook playboooks/configure_hosts_for_k8s.yml
---
- hosts: kubernetes-cluster
  vars_files:
    - ../vars/config.yml
  tasks:
    - name: Create VMs
      include_tasks: ../tasks/create-vm.yml
      loop: 
        - { name: 'kubernetes-master', ip: '192.168.56.101' }
        - { name: 'kubernetes-node1', ip: '192.168.56.102' }
        - { name: 'kubernetes-node2', ip: '192.168.56.103' }
        - { name: 'kubernetes-node3', ip: '192.168.56.104' }
        - { name: 'kubernetes-master-replica', ip: '192.168.56.110' }
...
